fix: remove white spaces from subject entries before committing
CDL-Dryad/dryad-app pull request #1479
Opened 2024-01-16 15:39 UTC by DragosIorgulescu

2024-01-16 23:15 UTC, ryscher commented on spec/requests/stash_datacite/subjects_controller_spec.rb
> +        post '/stash_datacite/subjects/create', params: params_hash, headers: default_authenticated_headers, as: :json
Normally, we only use the spec/requests to test API calls. You're calling a Rails route here, so I don't know if we have equivalent authentication paths.

Maybe this test would be better as a feature test, using the UI components?

2024-01-17 10:45 UTC, ahamelers commented
@DragosIorgulescu running `rubocop -a` will fix most ruby linting issues automatically

2024-01-25 14:57 UTC, ahamelers requested changes
Please run rubocop and make sure it passes!

2024-01-30 02:14 UTC, ryscher commented
Looks good and tests well. We can figure out the authentication issue with the rspec later.

2024-01-30 02:14 UTC, merged